export const colorsData = [
  { name: 'Salmon', color: '#FA8072' },
  { name: 'Crimson', color: '#DC143C' },
  { name: 'Red', color: '#FF0000' },
  { name: 'Pink', color: '#FFC0CB' },
  { name: 'Coral', color: '#FF7F50' },
  { name: 'Tomato', color: '#FF6347' },
  { name: 'Orange', color: '#FFA500' },
  { name: 'Gold', color: '#FFD700' },
  { name: 'Yellow', color: '#FFFF00' },
  { name: 'Khaki', color: '#F0E68C' },
  { name: 'Lavender', color: '#E6E6FA' },
  { name: 'Thistle', color: '#D8BFD8' },
  { name: 'Plum', color: '#DDA0DD' },
  { name: 'Violet', color: '#EE82EE' },
  { name: 'Orchid', color: '#DA70D6' },
  { name: 'Fuchsia', color: '#FF00FF' },
  { name: 'Purple', color: '#800080' },
  { name: 'Indigo', color: '#4B0082' },
  { name: 'Lime', color: '#00FF00' },
  { name: 'Green', color: '#008000' },
  { name: 'Olive', color: '#808000' },
  { name: 'Teal', color: '#008080' },
  { name: 'Aqua', color: '#00FFFF' },
  { name: 'Aquamarine', color: '#7FFFD4' },
  { name: 'Turquoise', color: '#40E0D0' },
  { name: 'Blue', color: '#0000FF' },
  { name: 'Navy', color: '#000080' },
  { name: 'Cornsilk', color: '#FFF8DC' },
  { name: 'Bisque', color: '#FFE4C4' },
  { name: 'Wheat', color: '#F5DEB3' },
  { name: 'Tan', color: '#D2B48C' },
  { name: 'Peru', color: '#CD853F' },
  { name: 'Goldenrod', color: '#DAA520' },
  { name: 'Chocolate', color: '#D2691E' },
  { name: 'Sienna', color: '#A0522D' },
  { name: 'Brown', color: '#A52A2A' },
  { name: 'Maroon', color: '#800000' },
  { name: 'White', color: '#FFFFFF' },
  { name: 'Snow', color: '#FFFAFA' },
  { name: 'Azure', color: '#F0FFFF' },
  { name: 'Beige', color: '#F5F5DC' },
  { name: 'Ivory', color: '#FFFFF0' },
  { name: 'Linen', color: '#FAF0E6' },
  { name: 'Silver', color: '#C0C0C0' },
  { name: 'Gray', color: '#808080' },
  { name: 'Black', color: '#000000' },
]

export const generateColor = () => {
  const randomIndex = Math.floor(Math.random() * colorsData.length)
  return colorsData[randomIndex].color
}
